// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBrief24.Models;

#nullable disable

namespace OnlineBrief24.Migrations
{
    [DbContext(typeof(OnlineBrief24Context))]
    partial class OnlineBrief24ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineBrief24.Models.Dispatches", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParametersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParametersId");

                    b.ToTable("Dispatches");
                });

            modelBuilder.Entity("OnlineBrief24.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DispatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Document")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParametersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId");

                    b.HasIndex("ParametersId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("OnlineBrief24.Models.Parameters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Colored")
                        .HasColumnType("bit");

                    b.Property<bool>("Envelope")
                        .HasColumnType("bit");

                    b.Property<bool>("Mode")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentSlip")
                        .HasColumnType("int");

                    b.Property<int>("RegisteredMail")
                        .HasColumnType("int");

                    b.Property<string>("Reserve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShippingZone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("OnlineBrief24.Models.Dispatches", b =>
                {
                    b.HasOne("OnlineBrief24.Models.Parameters", "Parameters")
                        .WithMany()
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("OnlineBrief24.Models.File", b =>
                {
                    b.HasOne("OnlineBrief24.Models.Dispatches", "Dispatch")
                        .WithMany("File")
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBrief24.Models.Parameters", "Parameters")
                        .WithMany("Files")
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatch");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("OnlineBrief24.Models.Dispatches", b =>
                {
                    b.Navigation("File");
                });

            modelBuilder.Entity("OnlineBrief24.Models.Parameters", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
